// Generated by WrapperBuilder. Do not edit — edit the script instead.
(function () {
    "use strict";
    if (!window.__inj) { return; }
    window.__inj.register("speed-hud", [{"host":"","hostKind":"any","path":"*","scheme":"any"}], function (GM) {
        var GM_onCleanup = GM.onCleanup;
        var GM_onRouteChange = GM.onRouteChange;
        var GM_addStyle = GM.addStyle;
        var GM_log = GM.log;
        var GM_info = GM.info;
        var GM_setValue = GM.setValue;
        var GM_getValue = GM.getValue;
        var GM_deleteValue = GM.deleteValue;
        var GM_listValues = GM.listValues;
/* ---- user source begins ---- */
// ==UserScript==
// @name        Playback speed
// @description Adds a speed control to any video, and remembers your choice per site.
// @version     1.0.0
// @match       <all_urls>
// @run-at      document-end
// @world       page
// ==/UserScript==

// §2 of the brainstorm: "Playback speed control → built-in script speed-hud".
//
// Sites that offer speed at all bury it in a menu, cap it at 2x, and forget it
// between videos. This is one tap, goes to 4x, and persists per hostname.
//
// document-end, not document-start: it needs a DOM to attach to. The rate is
// re-applied when new videos appear, because an SPA swapping the player would
// otherwise silently reset it.

(function () {
    "use strict";

    var STEPS = [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 3, 4];
    var KEY = "rate:" + location.hostname;
    var rate = 1;
    var hud = null;

    function videos() {
        return Array.prototype.slice.call(document.querySelectorAll("video"));
    }

    function apply() {
        var list = videos();
        for (var i = 0; i < list.length; i++) {
            // Assigning an unchanged rate still fires `ratechange`, and some
            // players listen for it and fight back.
            if (list[i].playbackRate !== rate) {
                list[i].playbackRate = rate;
            }
        }
        if (hud) {
            // Only when it actually changes. The observer below watches the
            // whole document, and the HUD is in the document — writing
            // textContent unconditionally makes apply() trigger the observer,
            // which calls sync(), which calls apply(). That is an infinite
            // loop that pegs the CPU and hangs the page on any video.
            var label = rate === 1 ? "1x" : String(rate) + "x";
            if (hud.textContent !== label) {
                hud.textContent = label;
            }
        }
    }

    function step(direction) {
        var index = STEPS.indexOf(rate);
        if (index < 0) {
            index = STEPS.indexOf(1);
        }
        index += direction;
        if (index < 0) {
            index = 0;
        }
        if (index >= STEPS.length) {
            index = STEPS.length - 1;
        }
        rate = STEPS[index];
        apply();
        try {
            // Persistence must never be able to break the control itself.
            Promise.resolve(GM_setValue(KEY, rate)).catch(function () {});
        } catch (e) {
            /* ignored */
        }
    }

    function build() {
        var box = document.createElement("div");
        box.setAttribute("data-oriel-speed", "1");
        box.style.cssText = [
            "position:fixed", "z-index:2147483647", "right:12px", "bottom:96px",
            "display:flex", "align-items:center", "gap:2px",
            "font:600 13px -apple-system,system-ui,sans-serif",
            "background:rgba(0,0,0,.72)", "color:#fff", "border-radius:14px",
            "padding:4px 6px", "backdrop-filter:blur(6px)",
            // Without this the HUD swallows taps meant for the player.
            "user-select:none", "-webkit-user-select:none"
        ].join(";");

        function button(label, onTap) {
            var b = document.createElement("button");
            b.textContent = label;
            b.style.cssText = [
                "all:unset", "cursor:pointer", "padding:4px 8px",
                "min-width:20px", "text-align:center", "border-radius:10px"
            ].join(";");
            b.addEventListener("click", function (event) {
                // The player is usually listening for clicks on everything.
                event.preventDefault();
                event.stopPropagation();
                onTap();
            });
            return b;
        }

        hud = document.createElement("span");
        hud.style.cssText = "min-width:30px;text-align:center";

        box.appendChild(button("−", function () { step(-1); }));
        box.appendChild(hud);
        box.appendChild(button("+", function () { step(1); }));
        (document.body || document.documentElement).appendChild(box);
        return box;
    }

    // Only where there is something to control. A speed control on a page with
    // no video is clutter.
    function sync() {
        var hasVideo = videos().length > 0;
        if (hasVideo && !box) {
            box = build();
        }
        if (box) {
            box.style.display = hasVideo ? "flex" : "none";
        }
        if (hasVideo) {
            apply();
        }
    }

    var box = null;

    // Render first, then refine. Gating the whole control behind the storage
    // promise meant that if the bridge was unavailable — or simply rejected —
    // the feature silently never appeared, with no error anyone would see.
    // A remembered rate is a nicety; a speed control that shows up is the
    // feature.
    sync();

    try {
        Promise.resolve(GM_getValue(KEY, 1))
            .then(function (saved) {
                var value = Number(saved);
                if (STEPS.indexOf(value) >= 0) {
                    rate = value;
                    apply();
                }
            })
            .catch(function () {
                /* no persistence available; 1x is a fine default */
            });
    } catch (e) {
        /* likewise */
    }

    // Players are created, swapped and re-created constantly on an SPA, and a
    // new element starts at 1x.
    // Mutations originating inside our own control are ignored outright: the
    // guard in apply() already breaks the feedback loop, but relying on one
    // equality check to prevent a page-hanging spin is too fragile for whoever
    // edits this next.
    var observer = new MutationObserver(function (records) {
        for (var i = 0; i < records.length; i++) {
            var target = records[i].target;
            if (box && (target === box || box.contains(target))) {
                continue;
            }
            sync();
            return;
        }
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });

    // A player that resets the rate itself gets overridden back. Named, not
    // anonymous, so cleanup can actually remove them — an anonymous listener
    // here survives teardown and keeps forcing the rate after the user has
    // switched the script off, which makes "turn it off and see" useless as a
    // diagnostic.
    function onRateChange() {
        apply();
    }

    document.addEventListener("ratechange", onRateChange, true);
    document.addEventListener("loadedmetadata", onRateChange, true);

    GM_onCleanup(function () {
        observer.disconnect();
        // Before resetting the rate, or onRateChange puts it straight back.
        document.removeEventListener("ratechange", onRateChange, true);
        document.removeEventListener("loadedmetadata", onRateChange, true);

        if (box && box.parentNode) {
            box.parentNode.removeChild(box);
        }
        var list = videos();
        for (var i = 0; i < list.length; i++) {
            list[i].playbackRate = 1;
        }
    });
})();

/* ---- user source ends ---- */
    }, "document-end");
})();