// Generated by WrapperBuilder. Do not edit — edit the script instead.
(function () {
    "use strict";
    if (!window.__inj) { return; }
    window.__inj.register("visibility-spoof", [{"host":"","hostKind":"any","path":"*","scheme":"any"}], function (GM) {
        var GM_onCleanup = GM.onCleanup;
        var GM_onRouteChange = GM.onRouteChange;
        var GM_addStyle = GM.addStyle;
        var GM_log = GM.log;
        var GM_info = GM.info;
        var GM_setValue = GM.setValue;
        var GM_getValue = GM.getValue;
        var GM_deleteValue = GM.deleteValue;
        var GM_listValues = GM.listValues;
/* ---- user source begins ---- */
// ==UserScript==
// @name        Keep playing in background
// @description Hides the fact that the page was backgrounded, so sites that pause themselves on visibilitychange keep playing.
// @version     1.0.0
// @match       <all_urls>
// @run-at      document-start
// @world       page
// ==/UserScript==

// Why this exists, and why it is a headline feature rather than a nicety:
//
// There are two completely different reasons audio stops when you leave a page.
// One is the platform suspending WebKit's media process — nothing JavaScript
// can do about that. The other is the *page itself* choosing to pause, because
// it saw `visibilitychange` and decided you were not watching. YouTube does
// this. The two look identical from the outside and have different fixes, and
// only this one is fixable from here.
//
// docs/decisions/004-background-audio-unverified.md promoted this to
// load-bearing precisely because it is orthogonal to the audio session: it
// works, or fails, independently of whether background audio survives at all.
//
// MUST run at document-start. Overriding `document.hidden` after the page has
// already installed its `visibilitychange` handler accomplishes nothing — the
// handler is registered, and it will fire.

(function () {
    "use strict";

    var doc = document;

    // Keep the originals so cleanup can put the page back exactly as it was.
    // A built-in the user toggles off must leave no trace, or "turn it off and
    // see if that fixes it" stops being a reliable diagnostic.
    var originals = {
        hidden: Object.getOwnPropertyDescriptor(Document.prototype, "hidden")
            || Object.getOwnPropertyDescriptor(doc, "hidden"),
        visibilityState: Object.getOwnPropertyDescriptor(Document.prototype, "visibilityState")
            || Object.getOwnPropertyDescriptor(doc, "visibilityState"),
        webkitHidden: Object.getOwnPropertyDescriptor(Document.prototype, "webkitHidden")
            || Object.getOwnPropertyDescriptor(doc, "webkitHidden"),
        webkitVisibilityState:
            Object.getOwnPropertyDescriptor(Document.prototype, "webkitVisibilityState")
            || Object.getOwnPropertyDescriptor(doc, "webkitVisibilityState")
    };

    function forceValue(name, value) {
        try {
            Object.defineProperty(doc, name, {
                configurable: true,
                get: function () {
                    return value;
                }
            });
            return true;
        } catch (e) {
            // Some engine or another page script may have made it
            // non-configurable. Report rather than fail silently — a media
            // feature that quietly does nothing is worse than one that says so.
            GM_log("could not override document." + name + ": " + e);
            return false;
        }
    }

    forceValue("hidden", false);
    forceValue("visibilityState", "visible");
    // Legacy prefixed forms: plenty of shipped player code still reads these.
    forceValue("webkitHidden", false);
    forceValue("webkitVisibilityState", "visible");

    // Overriding the properties is only half of it. The event still fires, and
    // a page that listens for it does not need to read `document.hidden` — it
    // can just pause on the event alone. So swallow the event too.
    //
    // Captured on `window`, which is the first hop of the capture phase, before
    // anything registered on `document` or via `document.onvisibilitychange`.
    function swallow(event) {
        event.stopImmediatePropagation();
        event.stopPropagation();
    }

    var swallowed = ["visibilitychange", "webkitvisibilitychange"];
    for (var i = 0; i < swallowed.length; i++) {
        window.addEventListener(swallowed[i], swallow, true);
    }

    GM_onCleanup(function () {
        for (var j = 0; j < swallowed.length; j++) {
            window.removeEventListener(swallowed[j], swallow, true);
        }
        var names = ["hidden", "visibilityState", "webkitHidden", "webkitVisibilityState"];
        for (var k = 0; k < names.length; k++) {
            var name = names[k];
            try {
                // Deleting the own property restores the prototype's accessor,
                // which is where these live natively.
                delete doc[name];
                if (originals[name] && !(name in doc)) {
                    Object.defineProperty(doc, name, originals[name]);
                }
            } catch (e) {
                /* nothing useful to do */
            }
        }
    });
})();

/* ---- user source ends ---- */
    }, "document-start");
})();