import Foundation

/// Builds the JavaScript each user script is injected as.
///
/// The wrapper is generated in Swift and the user's source is embedded in it
/// **literally, as code** — never as a string that something later evaluates.
/// That is not a stylistic choice: a user script is exempt from the page's
/// Content-Security-Policy, but `eval` and `new Function` inside that script
/// are not. Any design that ships source as data and evaluates it at runtime
/// dies on every strict-CSP site, which includes most sites worth scripting.
///
/// Because the source is embedded as code, there is nothing to escape and no
/// injection surface. The only thing that can go wrong is the user writing
/// unbalanced braces, which is a syntax error in their own script.
public enum WrapperBuilder {

    /// Wrap `source` for `metadata`, identified by `id`.
    ///
    /// The generated code registers with the prelude runtime and returns; it
    /// never decides for itself whether to run. Matching, re-entry and cleanup
    /// all live in one place (`window.__inj`) rather than being recompiled into
    /// every script — see `docs/decisions/005-spa-reentry.md`.
    public static func wrap(id: String, metadata: UserScriptMetadata, source: String) -> String {
        let descriptors = metadata.matches.map { $0.descriptor }
        let patternsJSON = encode(descriptors)
        let idJSON = jsString(id)

        return """
            // Generated by WrapperBuilder. Do not edit — edit the script instead.
            (function () {
                "use strict";
                if (!window.__inj) { return; }
                window.__inj.register(\(idJSON), \(patternsJSON), function (GM) {
                    var GM_onCleanup = GM.onCleanup;
                    var GM_onRouteChange = GM.onRouteChange;
                    var GM_addStyle = GM.addStyle;
                    var GM_log = GM.log;
                    var GM_info = GM.info;
                    var GM_setValue = GM.setValue;
                    var GM_getValue = GM.getValue;
                    var GM_deleteValue = GM.deleteValue;
                    var GM_listValues = GM.listValues;
            /* ---- user source begins ---- */
            \(source)
            /* ---- user source ends ---- */
                });
            })();
            """
    }

    /// A JavaScript string literal, escaped by hand.
    ///
    /// Not `JSONEncoder`: encoding a bare `String` is a top-level JSON
    /// *fragment*, which Foundation has historically refused, and a silent
    /// failure here would emit a broken literal into every wrapper. Doing it
    /// explicitly is a dozen lines and cannot surprise anyone.
    static func jsString(_ value: String) -> String {
        var out = "\""
        for character in value.unicodeScalars {
            switch character {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            case "\u{2028}": out += "\\u2028"
            case "\u{2029}": out += "\\u2029"
            default:
                if character.value < 0x20 {
                    out += String(format: "\\u%04x", character.value)
                } else {
                    out.unicodeScalars.append(character)
                }
            }
        }
        return out + "\""
    }

    /// JSON that is also safe as a JavaScript literal.
    ///
    /// U+2028 and U+2029 are legal inside JSON strings but were line
    /// terminators in JavaScript before ES2019 — unescaped, they can end a
    /// statement in the middle of a string. Escaping them costs nothing and
    /// removes a failure that would only ever show up on one exotic site.
    private static func encode<T: Encodable>(_ value: T) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        guard let data = try? encoder.encode(value),
            let text = String(data: data, encoding: .utf8)
        else {
            // Only reachable if Foundation cannot encode a String or a struct
            // of Strings. An empty pattern list matches nothing, which is the
            // safe direction to fail.
            return "[]"
        }
        return
            text
            .replacingOccurrences(of: "\u{2028}", with: "\\u2028")
            .replacingOccurrences(of: "\u{2029}", with: "\\u2029")
    }
}
