// Generated by WrapperBuilder. Do not edit — edit the script instead.
(function () {
    "use strict";
    if (!window.__inj) { return; }
    window.__inj.register("hide-shorts", [{"host":"youtube.com","hostKind":"suffix","path":"\/*","scheme":"any"}], function (GM) {
        var GM_onCleanup = GM.onCleanup;
        var GM_onRouteChange = GM.onRouteChange;
        var GM_addStyle = GM.addStyle;
        var GM_log = GM.log;
        var GM_info = GM.info;
        var GM_setValue = GM.setValue;
        var GM_getValue = GM.getValue;
        var GM_deleteValue = GM.deleteValue;
        var GM_listValues = GM.listValues;
/* ---- user source begins ---- */
GM_addStyle("ytd-reel-shelf-renderer { display: none }");
GM_log("hid the shelf");
/* ---- user source ends ---- */
    }, "document-start");
})();